[app]
database_path = "./final_project.db"
poll_interval = 300
rain_district = "Central & Western"
aqhi_station = "Central/Western"
traffic_region = "Hong Kong Island"
use_mock_data = false

[api]
warnings_url = "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=warnsum&lang=en"
rainfall_url = "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=rhrread&lang=en"
aqhi_url = "https://dashboard.data.gov.hk/api/aqhi-individual?format=json"
traffic_url = "https://www.td.gov.hk/en/special_news/trafficnews.xml"

[mocks]
warnings = "hk_monitor/tests/data/warnings.json"
rainfall = "hk_monitor/tests/data/rainfall.json"
aqhi = "hk_monitor/tests/data/aqhi.json"
traffic = "hk_monitor/tests/data/traffic.json"
